INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Yüzyıllık Yalnızlık', 1, 1, '1967-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Bin Dokuz Yüz Seksen Dört', 1, 1, '1949-06-08');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Aşk ve Gurur', 2, 2, '1813-01-28');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Sense and Sensibility', 2, 2, '1811-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Suç ve Ceza', 3, 3, '1866-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Karamazov Kardeşler', 1, 3, '1880-11-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Sefiller', 1, 4, '1862-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Les Misérables', 1, 4, '1862-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Kırmızı Pazartesi', 1, 5, '1922-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Vadideki Zambak', 1, 5, '1901-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Hayvan Çiftliği', 4, 6, '1945-08-17');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Nineteen Eighty-Four', 4, 6, '1949-06-08');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Sineklerin Tanrısı', 4, 7, '1954-09-17');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Lord of the Flies', 4, 7, '1954-09-17');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Kısa ve Mutlu Yaşamı', 1, 8, '1958-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Catcher in the Rye', 1, 8, '1951-07-16');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Doğu Ekspresinde Cinayet', 3, 9, '1934-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Murder on the Orient Express', 3, 9, '1934-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Simyacı', 1, 10, '1988-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Alchemist', 1, 10, '1988-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('İkinci Şans', 2, 11, '2004-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Second Chance', 2, 11, '2004-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('İstanbul Hatırası', 1, 12, '2005-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Museum of Innocence', 1, 12, '2005-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('İki Şehrin Hikayesi', 1, 13, '1859-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('A Tale of Two Cities', 1, 13, '1859-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Siyah İnci', 2, 14, '1901-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Black Pearl', 2, 14, '1901-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Martı', 1, 15, '1896-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Seagull', 1, 15, '1896-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Dorian Gray in Portresi', 1, 16, '1890-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('The Picture of Dorian Gray', 1, 16, '1890-01-01');
INSERT INTO book (book_name, genre_id, author_id, public_date) VALUES ('Kırmızı ve Siyah', 1, 17, '1830-08-25');

INSERT INTO genre (genre_name) VALUES  ('Roman');
INSERT INTO genre (genre_name) VALUES  ('Aşk');
INSERT INTO genre (genre_name) VALUES  ('Polisiye');
INSERT INTO genre (genre_name) VALUES  ('Tarihi');

INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Gabriel', '', 'García Márquez', '1927-03-06', 'Kolombiya');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('George', 'Orwell', '', '1903-06-25', 'İngiltere');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Fyodor', '', 'Dostoyevsky', '1821-11-11', 'Rusya');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Victor', '', 'Hugo', '1802-02-26', 'Fransa');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Sabahattin', '', 'Ali', '1907-02-25', 'Türkiye');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('J.D.', '', 'Salinger', '1919-01-01', 'ABD');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Agatha', 'Mary Clarissa', 'Christie', '1890-09-15', 'İngiltere');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Paulo', '', 'Coelho', '1947-08-24', 'Brezilya');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Michael', 'C.', 'Burgess', '1917-02-25', 'İngiltere');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Orhan', '', 'Pamuk', '1952-06-07', 'Türkiye');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Danielle', '', 'Steel', '1947-08-14', 'ABD');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Charles', '', 'Dickens', '1812-02-07', 'İngiltere');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Scott', 'O''Dell', '', '1898-05-23', 'ABD');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Anton', 'Pavlovich', 'Chekhov', '1860-01-29', 'Rusya');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Arthur', '', 'Miller', '1915-10-17', 'ABD');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Oscar', 'Fingal O''Flahertie Wills', 'Wilde', '1854-10-16', 'İrlanda');
INSERT INTO author (first_name, middle_name, last_name, birth_date, country) VALUES ('Stendhal', '', '', '1783-01-23', 'Fransa');
